my_string = input("Введите произвольный текст: ")
print("Количество символов введенного текста: ",len(my_string))
print("Введенная строка в верхнем регистре:" , my_string .upper())
print("Веденная строка в нижнем регистре:" , my_string .lower())
print("Введенный текст без пробелов: " , my_string .replace(" ", ""))